
version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=lab
      - DOCKER_INFLUXDB_INIT_BUCKET=signals
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=dev-token
    volumes:
      - influx-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:10.4.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  bridge:
    image: python:3.11-slim
    container_name: mqtt-influx-bridge
    depends_on:
      - mosquitto
      - influxdb
    volumes:
      - ./bridge:/app
    working_dir: /app
    command: bash -lc "pip install --no-cache-dir paho-mqtt influxdb-client && python mqtt_to_influx.py"
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_TOPIC=plataforma/anomalia
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=dev-token
      - INFLUX_ORG=lab
      - INFLUX_BUCKET=signals

volumes:
  mosquitto-data:
  mosquitto-log:
  influx-data:
  grafana-data:
