
version: "3.8"
services:
  influxdb:
    image: influxdb:2.7
    ports: ["8086:8086"]
    volumes:
      - influx-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=lab
      - DOCKER_INFLUXDB_INIT_BUCKET=signals

  grafana:
    image: grafana/grafana:10.4.3
    ports: ["3000:3000"]
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  influx-data:
  grafana-data:
